---
- hosts: localhost
  vars:
    tomcat_path: /opt
    tomcat_version: 10.1.19
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.zip
  tasks:
  - name: check file tomcat zip file existance
    stat:
      path: "{{ tomcat_path }}/apache-tomcat-{{ tomcat_version }}.zip"
    register: tomcat_file_existance
  - name: print tomcat_file_existance
    debug:
      msg: "{{ tomcat_file_existance }}"
  - name: download tomcat zip file
    get_url:
      url: "{{ tomcat_url }}"
      dest: "{{ tomcat_path }}"
    when: not tomcat_file_existance.stat.exists
  - name: extract zip file
    unarchive:
      src: "{{ tomcat_path }}/apache-tomcat-{{ tomcat_version }}.zip"
      dest: "{{ tomcat_path }}"
      remote_src: yes
  - name: lookup files with a certain pattern
    find:
      paths: "{{ tomcat_path }}/apache-tomcat-{{ tomcat_version }}/bin"
      file_type: file
      patterns: "*.sh"
    register: filelist
  - name: change permissions
    file:
      path: "{{ item.path }}"
      state: file
      mode: "0775"
    with_items: "{{ filelist.files }}"
  - name: create tomcat user
    user:
      name: tomcat
      state: present
  - name: change ownership of tomcat home directory
    file:
      path: "{{ tomcat_path }}/apache-tomcat-{{ tomcat_version }}"
      owner: tomcat
      group: tomcat
      state: directory
      recurse: yes
  - name: modify values with variable under service file
    template:
      src: tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: 0755
  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes
  - name: enable tomcat startup
    service:
      name: tomcat
      state: restarted
